apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: default
spec:
  size: 1
  resources: {}
  clusterName: cluster1
  serverVersion: 3.11.6
  racks:
    - name: r1
  serverType: cassandra
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
      storageClassName: local-storage
  managementApiAuth:
    insecure: {}
